# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RinggoldRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=512, null=True)),
                ('country_code', models.CharField(max_length=8, null=True)),
                ('country_name', models.CharField(max_length=512, null=True)),
                ('org_type', models.CharField(max_length=128, null=True)),
                ('region', models.CharField(max_length=512, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('ringgold_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
